# Generated by Django 5.2 on 2025-05-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookmaker_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='kurs_druzyna1',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name='event',
            name='kurs_druzyna2',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
