# Generated by Django 5.2.1 on 2025-05-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookmaker_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
