# Generated by Django 5.2 on 2025-05-26 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookmaker_app', '0002_event_kurs_druzyna1_event_kurs_druzyna2'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakladyuzytkownika',
            name='event1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Bookmaker_app.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zakladyuzytkownika',
            name='kurs',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zakladyuzytkownika',
            name='wytypowany',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
