# Generated by Django 5.2 on 2025-05-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookmaker_app', '0003_zakladyuzytkownika_event1_zakladyuzytkownika_kurs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakladyuzytkownika',
            name='wygrana',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
