# Generated by Django 5.2.1 on 2025-05-27 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookmaker_app', '0004_zakladyuzytkownika_wygrana'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zakladyuzytkownika',
            name='wygrana',
        ),
        migrations.AlterField(
            model_name='zakladyuzytkownika',
            name='wytypowany',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmaker_app.drużyna'),
        ),
    ]
