# Generated by Django 5.2.1 on 2025-06-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookmaker_app', '0005_remove_zakladyuzytkownika_wygrana_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('nadchodzacy', 'Nadchodzący'), ('trwa', 'Trwa'), ('zakonczony', 'Zakończony')], default='nadchodzacy', max_length=20),
        ),
    ]
